version: '3.1'

services:

  mongo:
    image: mongo:5.0.3
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: development
      MONGO_INITDB_ROOT_PASSWORD: testpassword
  
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: on-failure
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: development
      ME_CONFIG_MONGODB_ADMINPASSWORD: testpassword
      ME_CONFIG_MONGODB_URL: mongodb://development:testpassword@mongo:27017/
    depends_on:
      - mongo

  backend:
    build: backend
    restart: on-failure
    environment:
      DB_ADDRESS: mongodb://development:testpassword@mongo:27017
      PORT: :5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - mongo-express
  
  frontend:
    build: frontend
    restart: on-failure
    ports:
      - 5173:5173
    environment:
      - VITE_WEBSOCKET_URL=ws://localhost:5000/ws
    depends_on:
      - backend